# Introducción

La participación cívica entendida como la acción manifiesta a influir en las decisiones políticas del gobierno o en los resultados políticos (Ekman & Amnå, 2012), tiene profundos cambios en Chile desde el retorno a la democracia en 1990, configurando la paradoja actual del declive de la participación formal y el aumento de la participación activista. Por un lado, la participación formal que ocupa los canales institucionales para influir en las decisiones gubernamentales (Miranda, 2018; Miranda, Castillo & Sandoval-Hernández, 2017), registra un declive con la participación en elecciones nacionales, siendo una de las más bajas de América Latina (Programa de las Naciones Unidas para el Desarrollo [PNUD], 2017a). Ante la ruptura de fondo entre política y sociedad, este declive es síntoma del debilitamiento de los canales institucionales de participación, la crisis de legitimidad del sistema político y la despartidización (Garretón, 2016; Ruiz, 2015; Somma, 2017). Sin embargo, por otro lado, la participación activista que ocupa canales alternativos para influir en los resultados del sistema político (Miranda, 2018; Miranda et al., 2017), se caracteriza por su aumento al alero de protestas desde la década del 2000, cultivando una autonomía respecto a las instituciones tradicionales de representación política (Bidegain, 2015; Roberts, 2016; Somma & Bargsted, 2015; Somma & Medel, 2017). 

La literatura señala que el aumento de la participación activista es una alternativa para presionar al sistema político con demandas ciudadanas (PNUD, 2019), lo que es considerado como un proceso de (re)politización de la sociedad chilena al margen de la institucionalidad (e.g., Donoso & von Bulow, 2017; PNUD, 2019; Roberts, 2016). No obstante, la legitimidad de la democracia chilena es puesta en cuestión, precisamente por su baja representación de intereses y expectativas ciudadanas en la política institucional (PNUD, 2019). Esta situación se vuelve aún más crítica por la desigualdad de voz política, en tanto tienen menos voz en el sistema político y en instancias de participación cívica (i.e., en participación formal y activista) aquellos de menor estatus social (e.g., Bargsted, Somma, Campos & Joignant, 2017; Corvalan & Cox, 2015; Roberts, 2016). La evidencia señala que sucede lo mismo con la participación cívica de los jóvenes (e.g., Corvalan & Cox, 2015; Rozas & Somma, 2020), pero particularmente se encuentran doblemente mal representados por la democracia, ya que además la edad es un factor de desigualdad política que afecta negativamente su participación formal (e.g., Bargsted et al., 2017; Contreras & Navia, 2013; Toro, 2008).

Producto de la preocupación por los bajos niveles de participación cívica acumulada en la población más joven, un importante cuerpo de investigación se pregunta por como se puede promover previamente su participación, mediante la formación ciudadana en las escuelas. Desde un horizonte normativo, se espera que las escuelas sean un espacio donde se prepare a los estudiantes para participar a futuro, tanto en la comunidad política como en la vida política (Hess & McAvoy, 2015). Esto se debe a que la escuela es una institución mediadora, en la cual los estudiantes se enfrentan a una ‘mini-política’ y practican lo que significa ser ciudadanos de una organización política más grande (Flanagan, 2016). De ese modo, la escuela es concebida como un espacio de socialización política (Cumsille & Martínez, 2015; Deimel, Hoskins & Abs, 2020; Neundorf, Niemi & Smets, 2016), pues en ella se cristalizan identidades políticas, valores y comportamientos que perdurarán en la vida de los estudiantes (Neundorf & Smets, 2017). A partir de la adquisición de conocimientos sobre como funciona el sistema político, los estudiantes pueden desarrollar valores y normas democráticas que promuevan una participación ciudadana activa (Youniss & Levine, 2009).

Múltiples investigaciones en ciencias sociales estudian empíricamente si la formación ciudadana en las escuelas promueve la intención de participación formal y activista de los estudiantes (e.g., Blaskó, Dinis da Costa & Vera-Toscano, 2019; Deimel et al., 2020; Castillo, Miranda, Bonhomme, Cox & Bascopé, 2015a; Eckstein & Noack, 2016; Isac, Maslowski, Creemers & van der Werf, 2014; Quintelier & Hooghe, 2013; Treviño, Villalobos, Béjares & Naranjo, 2019). No solo a partir del mandato explícito del currículum formal, sino también mediante un currículum oculto no intencionado que emerge de la cultura y el clima escolar (Apple, 1980; González, 2018). No obstante, la evidencia enfatiza la relevancia de la socialización política de las familias, demostrando que los estudiantes de familias con menos estatus social tienen una menor intención de participación cívica (Miranda, Bonhomme, Cox & Bascopé, 2014; Castillo et al., 2015a; Kudrnáč, 2017; Manganelli, Lucidi & Alivernini, 2015; Miranda, 2018; Neundorf, et al., 2016). Este resultado explicado comúnmente por el modelo de recursos (e.g., Castillo et al., 2014; Castillo et al., 2015a; Miranda, 2018), es conceptualizado como la transmisión intergeneracional de la desigualdad política (Brady, Schlozman & Verba, 2015; Miranda, 2018; Schlozman, Verba & Brady, 2012). 

La relevancia de los recursos parentales y la evidencia que respalda la transmisión de los resultados políticos a sus hijos (Brady et al. 2015; Castillo et al., 2014; Miranda, 2018; Schlozman et al. 2012), vuelve crucial el rol de socialización política de las escuelas para paliar la desigualdad política en los estudiantes. Si bien existe una vasta evidencia sociológica sobre los factores sociodemográficos implicados en la desigualdad de voz política en población adulta y joven (e.g., Bargsted et al., 2017; Corvalan & Cox, 2015; Roberts, 2016; Rozas & Somma, 2020), la evidencia proporcionada por la disciplina es menor cuanto se trata de la desigualdad política en los estudiantes, ante la cobertura puesta en la transmisión del logro educacional o el estudio de la reproducción social (Miranda, 2018). Es por eso que, la línea de investigación que se preocupa por la capacidad del sistema escolar de desafiar el habitus familiar (c.f. Peña, 2015), sigue la premisa de que la escuela no es completamente un espacio de producción social (c.f. Bourdieu & Passeron, 1977), pues también en ella está la posibilidad de promover la participación cívica en los estudiantes más desfavorecidos (Bonhomme, Cox, Tham & Lira, 2015). 

Recientes investigaciones se preocupan por como mitigar la brecha generada por el vínculo entre el estatus social familiar y la intención de participación cívica de los estudiantes, a partir de la formación ciudadana en la escuela. La evidencia empírica prueba como mitigadores de este vínculo, al clima abierto en el aula, la participación en la escuela, la participación en actividades cívicas, la participación en decisiones escolares y el aprendizaje formal de ciudadanía (Campbell, 2008; Castillo et al., 2015a; Deimel, et al., 2020; Eckstein & Noack, 2016; Gainous & Martens, 2012; Hoskins, Janmaat & Melis, 2017; Kudrnáč, 2017; Neundorf et al., 2016). Sin embargo, a menudo los estudiantes más desfavorecidos tienen un acceso desigual a estos mitigadores que brinda la formación ciudadana (Deimel et al., 2020; Hoskins et al., 2017), lo que incentiva la búsqueda de más oportunidades para reducir la brecha generada por el estatus social familiar. 

Dicho lo anterior, hasta ahora es escasa la evidencia sobre la contribución de la justicia percibida por los estudiantes en la escuela, la cual se caracteriza por una operacionalización que se limita a la percepción sobre el trato justo de los profesores (c.f. Eckstein & Noack, 2016). Plegarse a los aportes teóricos y empíricos que desarrolla la sociología y la psicología social con el sentido de justicia en la escuela (e.g., Resh & Sabbagh, 2016; Sabbagh & Resh, 2016; Sabbagh, Resh, Mor & Vanhuysse, 2006), puede subsanar la anterior limitación al estudiar la distribución meritocrática de las notas como justicia distributiva (Resh, 2010; Resh & Sabbagh, 2013; Sabbagh et al., 2006; Sabbagh & Resh, 2016) y la justicia de los profesores en las relaciones con sus estudiantes como justicia relacional (Čiuladienė & Račelytė, 2016; Claus, Chory & Malachowski, 2012). En este sentido, la presente investigación tiene por objetivo general *analizar el efecto del sentido de justicia en la escuela sobre la intención de participación cívica de los estudiantes y su efecto mitigador de la brecha generada por el estatus social familiar.* 

La relevancia de investigar el sentido de justicia en la escuela, se debe a que es una experiencia escolar significativa para los estudiantes (Dalbert, 2004), al mismo tiempo que estudios clásicos sobre el desarrollo político de los jóvenes señalan que la justicia social es una motivación importante para la participación cívica (Flanagan & Sherrod, 1998). Al respecto, la literatura señala que el sentido de justicia en la escuela es parte del currículum oculto de las escuelas (Resh, 2010, 2018; Resh & Sabbagh, 2013, 2014, 2017), pudiendo cumplir un rol latente en la formación ciudadana de los estudiantes. La reciente evidencia empírica muestra resultados alentadores acerca de como contribuye la dimensión de justicia distributiva y relacional en la socialización cívica de los estudiantes (Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2018; Resh & Sabbagh, 2013, 2014, 2017), tal como sucede con la evidencia más cercana que prueba en particular el efecto sobre la intención de participación formal y activista (Eckstein & Noack, 2016; Isac et al., 2014; Quintelier & Hooghe, 2013; Treviño et al., 2019). Además, existe evidencia favorable sobre el acceso igualitario a la justicia distributiva (Resh, 2010; Resh & Dalbert, 2007) y los estudios más cercanos sugieren que la justicia relacional puede mitigar la brecha por estatus social familiar (e.g. Eckstein & Noack, 2016), lo que abre una valiosa oportunidad para paliar la desigualdad política en los estudiantes. 

Dicho de un modo general, al analizar el efecto del sentido de justicia en la escuela sobre la intención de participación cívica de los estudiantes, se busca aportar con evidencia que retome la preocupación por la baja participación acumulada de la población más jóven en Chile, considerando que las intenciones de participación de los estudiantes son un predictor de la participación cívica a futuro (Quintelier & Blais, 2016). Además, probar si el sentido de justicia en la escuela mitiga el vínculo entre el estatus social familiar y la intención de participación cívica, tiene como fondo la preocupación por la transmisión intergeneracional de la desigualdad política. En un contexto como el chileno, aquello toma relevancia por los crecientes niveles de desigualdad desde el regreso a la democracia (Flores, Sanhueza, Atria & Mayer, 2019) y el alto nivel de segregación socioeconómica del sistema escolar (Mizala & Torche, 2012; Santos & Elacqua, 2016; Valenzuela, Bellei, de los Ríos, 2014). Por lo tanto, se tiene como hipótesis general que *el sentido de justicia en la escuela tendrá un efecto positivo sobre la intención de participación cívica de los estudiantes y logrará mitigar la brecha generada por el estatus social familiar.*

En este estudio se trabaja con modelos lineales jerárquicos o modelos multinivel, a modo de realizar un análisis a nivel individual y a nivel escolar, tal como lo hacen otras investigaciones en el campo dedicadas a estudiar la intención de participación cívica (e.g., Castillo et al., 2015a; Deimel et al., 2020; Isac et al., 2014; Quintelier & Hooghe, 2013; Treviño et al., 2019). Por lo tanto, los objetivos específicos de la investigación son: a) analizar el efecto de la justicia distributiva a nivel individual y escolar sobre la intención de participación formal y activista de los estudiantes; b) analizar el efecto de la justicia relacional a nivel individual y escolar sobre la intención de participación formal y activista de los estudiantes; y c) analizar el efecto mitigador de la justicia distributiva y relacional a nivel individual, sobre el vínculo entre el estatus social familiar y la intención de participación formal y activista de los estudiantes. En tal sentido, la pregunta central que orienta la investigación es la siguiente: *¿Cómo afecta el sentido de justicia en la escuela sobre la intención de participación cívica de los estudiantes chilenos?*
