# Participación cívica en Chile

Para una democracia plena se necesita una ciudadanía que participe de la toma de decisiones colectivamente vinculantes (PNUD, 2019), a modo de ejercer un control sobre las autoridades e instituciones (Núñez, Osorio & Peit, 2018). No obstante, producto de la democracia protegida promovida desde la transición (1990) y la herencia de la dictadura militar de Augusto Pinochet (1973-1989), la democracia en Chile se considera como limitada, elitista o en crisis (Delamaza, 2010; Garretón & Garretón, 2010; Zarzuri, 2016). Según el PNUD (2019), el descontento hacia la democracia y la desconfianza hacia el sistema político, convive con un ethos republicano caracterizado por la alta valoración abstracta por la democracia, el voto, los partidos políticos y el estado de derecho. Para abordar la participación de los ciudadanos en un contexto como este, es menester considerar no solo su participación en elecciones dentro de la institucionalidad política, sino también otras formas de participación por fuera de la institucionalidad, pues ambas se encuentran a la base de los sistemas democráticos modernos (della Porta, 2013). 

La conceptualización de la participación política es un tema de profundo debate en la literatura, producto de la expansión en las formas de participar (van Deth, 2014). Los bajos niveles de participación en elecciones y la desconfianza hacia las instituciones de representación, son factores que han forzado la reconceptualización y apertura a más formas de participación política (Ekman & Amnå, 2012). En este sentido, actualmente la concepción de participación centrada en el voto conduce a un diagnóstico defectuoso, porque es ciega a la emergencia de otras formas de participación por fuera de la institucionalidad (Dalton, 2008, 2017; Dalton & Klingemann, 2007). Por lo tanto, interesa estudiar la participación formal como el voto, junto con la participación activista que considera actividades extra institucionales como la protesta, a modo de capturar la participación tanto dentro como fuera de la institucionalidad (Miranda, 2018; Miranda et al., 2017). Ambas formas de participación son conceptualizadas como dimensiones de la participación cívica (Miranda et al., 2017), teniendo en común la toma de acción manifesta a influir en las decisiones políticas del gobierno o en los resultados políticos (Ekman & Amnå, 2012).

Para el caso de Chile, múltiples investigaciones con un enfoque histórico-interpretativo, señalan que la actual participación formal y activista encuentra su configuración en la herencia del modelo socioeconómico y político-institucional de la dictadura, junto con la democracia protegida a cargo de los gobiernos de la Concertación (1990-2010). Ambas formas de participación cívica tienen cambios profundos desde el retorno a la democracia (1990), derivando en la actual paradoja del declive de la participación formal y el aumento de la participación activista. 

Por un lado, el plebiscito de 1988 y las elecciones presidenciales de 1989, se caracterizaron por la alta inscripción y participación electoral (Contreras & Navia, 2013; Navia, 2004; Toro, 2008), pero estos indicadores bajan sostenidamente en las últimas décadas (e.g., Bargsted, Somma & Muñoz-Rojas, 2019; Contreras & Navia, 2013; Corvalan & Cox, 2015). Algunos investigadores señalan que el modelo político-institucional de la dictadura preservado por los gobiernos de la Concertación, produjo trabas y desincentivos para la participación formal, como sucedió con el sistema del registro electoral y el sistema binominal (Corvalan & Cox, 2015; Garretón & Garretón, 2010; PNUD, 2017a; Siavelis, 2016; Treviño et al., 2019). Una de las consecuencias más profundas, fue la falta de competencia y alternativas políticas (Lechner, 1994), lo que condujo en el largo plazo a una despartidización, crisis de representación y desafección de la sociedad civil con la política (Garretón, 2016; Luna, 2016; Siavelis, 2016; Somma, 2017). Actualmente los niveles de participación en elecciones son de los más bajos en América Latina y la desconfianza hacia las instituciones políticas toma un tono crítico (PNUD, 2017a, 2019), mientras que las élites políticas progresivamente se alejan o encapsulan más respecto de sus bases sociales (Castiglioni & Rovira, 2016; Bargsted & Maldonado, 2018; Luna, 2016). 

Por otro lado, la década de 1980 se caracterizó por la cohesión entre partidos políticos y organizaciones sociales en torno al eje autoritarismo-democracia, lo que se tradujo en una serie de protestas en contra de la dictadura (Somma & Bargsted, 2015; Somma & Medel, 2017; Toro, 2008). No obstante, la década de 1990 con el retorno a la democracia, estuvo marcada por la ruptura de la relación entre los partidos y la ciudadanía organizada, a la falta de un enemigo común como la dictadura (Somma & Bargsted, 2015; Somma & Medel, 2017; Roberts, 2016). Las explicaciones para la consiguiente disminución de la participación activista, señalan los efectos nocivos de la atomización de la sociedad de mercado (Lechner, 1994; Somma & Medel, 2017), la desarticulación de los actores sociales en dictadura y la desmovilización hacia abajo promovida por la Concertación, ante el peligro que significaba la acción colectiva para la fragilidad de la democracia (Castiglioni & Rovira, 2016; Luna, 2016; Roberts, 2016; Somma & Bargsted, 2015; Somma & Medel, 2017). Sin embargo, las protestas aumentan desde la década del 2000 (Medel & Somma, 2016; Somma & Bargsted, 2015; Somma & Medel, 2017), en particular con las movilizaciones estudiantiles del 2006, para luego extenderse a una diversidad de grupos que antes estaban desmovilizados (Medel & Somma, 2016). 

El panorama actual de la participación cívica en Chile, evidencia la paradoja del declive de la participación formal y el aumento de la participación activista. Los intentos del sistema político para minimizar las desigualdades en vías de labrar un consenso nacional y fomentar la eficiencia tecnocrática de la elite política (Roberts, 2016), hizo de las protestas la principal estrategia para que sean escuchadas las demandas ciudadanas (Medel & Somma, 2016; Somma & Medel, 2017), ante el debilitamiento de los canales institucionales de representación política y las dificultades las élites políticas para procesar el malestar (Garretón, 2016; Luna, 2016; Ruiz, 2015; Somma, 2017; Somma & Bargsted, 2015; Somma & Medel, 2017). De este modo, el descontento por la contradicción entre los principios del orden social de la dictadura y, los principios de un modelo socioeconómico justo y un orden político democrático (Garretón, 2016), se comienza a manifestar en la arena pública con una creciente movilización social de distintos actores que desafían e impugnan al sistema político, al margen de la institucionalidad (e.g., Bidegain, 2015; Donoso & von Bülow, 2017; Somma, 2017; Somma & Bargsted, 2015).

Este proceso político de la ciudadanía al margen e incluso en contra de la política institucional (PNUD, 2019), es entendido como una (re)politización de la sociedad chilena (Donoso & von Bulow, 2017; PNUD, 2015, 2017a, 2019; Roberts, 2016), a pesar de coexistir con bajos niveles de identificación política, interés por la política y participación en elecciones (e.g., Bargsted et al., 2019; Núñez et al., 2018; PNUD, 2019). No obstante, este panorama es preocupante para la legitimidad de la democracia, no solo porque la baja participación formal afecta la representatividad de la diversidad de intereses y expectativas ciudadanas (PNUD, 2019), sino también por el déficit de una voz política igualitaria. En efecto, si otras formas de participación como la activista aumentan, sigue siendo problemático que solo unas voces se escuchen (Dalton, 2017). Una democracia sólida, inclusiva y participativa, debe tener como desafío superar la desigualdad política e incluir a todos los grupos sociales (PNUD, 2019).

Recientemente se han realizado investigaciones desde la ciencia política y la sociología, para explicar como afectan los factores que provocan las desigualdades de voz política en la participación de los ciudadanos (e.g., Bargsted et al., 2017; Dalton, 2017; Miranda, 2018; PNUD, 2017b; PNUD, 2019; Somma & Bargsted, 2018; Somma, Bargsted & Sánchez, 2020). La propuesta base es que, el grado de voz política para expresar intereses y demandas hacia el sistema político o en instancias de participación cívica (Dubrow, 2015 citado en PNUD, 2017b), son diferentes de acuerdo a las preferencias individuales y los factores sociodemográficos de los ciudadanos. La ciencia política y la sociología chilena sobre las preferencias individuales, aportan evidencia de que las personas con mayor participación formal (e.g., participación en elecciones), tienen una identificación política cargada hacia la derecha, participan más en organizaciones, confían más en instituciones políticas y tienen un mayor interés por la política (Bargsted et al., 2017; Castillo, Palacios, Joignant & Tham, 2015b; Contreras & Navia, 2013; Corvalan & Cox, 2015; Núñez et al., 2018). Mientras tanto, las personas con mayor participación activista (e.g., participación en protestas), se identifican más con la izquierda, participan más en organizaciones, tiene un mayor interés por la política, se identifican más con las causas sociales y creen en la justicia redistributiva (Bargsted et al., 2017; Castillo et al., 2015b; Ortiz-Inostroza & Lopez, 2017; Roberts, 2016). 

Los factores sociodemográficos que explican la desigualdad de voz política, son principalmente investigados por la sociología. La literatura internacional en base al modelo de recursos (Verba, Schlozman & Brady, 1995), el cual propone que los recursos económicos, educativos y estatus ocupacional inciden en una mayor propensión a la participación cívica, comprueba que quienes votan y asisten a protestas tienen un mayor estatus social (Brady et al., 1995; Dalton, 2017; Dalton, van Sickle & Weldon, 2010; Dubrow, Slomczynski & Tomescu-Dubrow, 2008; Lijphart, 1997; Marien, Hooghe & Quintelier, 2010; Verba et al., 1995). En el plano nacional, se confirma que aquellas personas con niveles educativos más bajos tienen una menor propensión a la participación formal (Bargsted et al., 2017; Contreras & Navia, 2013; Corvalan & Cox, 2015), como también a la participación activista (Bargsted et al., 2017; Castillo et al., 2015b; Núñez et al., 2018; Ortiz-Inostroza & Lopez, 2017; Roberts, 2016). Si bien existe evidencia de que sucede lo mismo con los niveles socioeconómicos más bajos (Bargsted et al., 2017; Contreras & Navia, 2013; Corvalan & Cox, 2015), algunas investigaciones señalan que en la participación activista tiene un efecto negativo (Roberts, 2016) o una relación no lineal (Ortiz-Inostroza & Lopez, 2017). Esta divergencia puede ser porque el efecto positivo del nivel socioeconómico ocurre en protestas que buscan generar cambios en un aspecto particular de la sociedad, a diferencia de las protestas por la supervivencia material y social (Somma et al., 2020). 

Siguiendo con los factores sociodemográficos de la desigualdad de voz política, existe un gran acuerdo de que edad es relevante para explicar la propensión a la participación formal y activista. No obstante, lo que sucede en este caso, es que la edad es un factor de desigualdad de voz política, dependiendo del tipo de participación cívica que se trate. De ese modo, la edad a la vez que es un factor de desigualdad política, configura en parte la paradoja de la participación cívica, expresada como el declive de la participación formal y el aumento de la participación activista. En lo sucesivo se precisa la preocupación por la participación cívica de los jóvenes, abordando las principales explicaciones y hallazgos, con el fin de abrir camino al estudio de la intención de participación cívica de los estudiantes. 

## Intención de participación cívica

La literatura señala que en el último tiempo disminuye la participación electoral y la membresía partidista de los jóvenes (definidos como personas entre 15 y 29 años), pero esto viene acompañado del aumento de su participación en otras formas de participación política, como es el caso de la participación activista (Dalton, 2006, 2017; Sandoval & Carvallo, 2019; Zarzuri, 2016). Por lo tanto, los bajos niveles de participación formal de los jóvenes, más que significar una apatía política y despolitización generalizada, es un rechazo al sistema político actual, las instituciones políticas y los canales formales de participación (Arias-Cardona & Alvarado, 2015; Instituto Nacional de la Juventud [INJUV], 2017; Sandoval & Carvallo, 2017; Zarzuri, 2016). La ‘nueva política’ de los jóvenes desde lo cotidiano y ‘lo político’ (Arias-Cardona & Alvarado, 2015; Escobar, 2019; INJUV, 2017; Sandoval & Carvallo, 2017, 2019; Zarzuri, 2016), asume una crítica a la concepción tradicional de democracia representativa, encapsulada en la participación formal y los márgenes institucionales de ‘la política’ (INJUV, 2017; Escobar, 2019; Zarzuri, 2016).

Un cuerpo importante de investigaciones en Chile, a partir de fenómenos generacionales y sociopolíticos, han explicado la baja participación formal y el aumento de la participación activista de los jóvenes. Por un lado, las explicaciones a la baja participación formal parten en la década de 1990 (i.e., luego de la transición a la democracia) con la apatía política juvenil, caracterizada por el desencanto, la pérdida de interés en el mundo público y el refugio en el mundo privado (Navia, 2004; Parker, 2000). En esta línea, otras investigaciones argumentan el cambio generacional en la cultura política de los jóvenes, al desconfiar de la institucionalidad política, alejarse de las actividades colectivas y evitar la identificación ideológica (Carlin, 2006; Toro, 2008). Explicaciones más recientes desde un enfoque sociopolítico, señalan que el declive de la participación electoral de los jóvenes se debe a su baja inscripción en los padrones electorales luego del plebiscito de 1989 (Contreras & Navia, 2013), derivando en el problema del reemplazo generacional, a raíz del sistema electoral heredado de la dictadura militar (Corvalan & Cox, 2015). Asimismo, otros estudios aducen que los jóvenes prefieren otras formas de participación por fuera de la institucionalidad, ante la pérdida de la afectividad vinculante con la participación formal (Escobar, 2019; INJUV, 2017; Zarzuri, 2016).

Por otro lado, el aumento de la participación activista de los jóvenes, no quiere decir que sean los únicos protagonistas de la movilización social del último tiempo (Garretón, Joignant, Somma & Campos, 2017), sino que son un actor social que crece y se fortalece por las movilizaciones estudiantiles en el período post autoritario (Sandoval & Carvallo, 2019). En este sentido, la literatura coincide en que se trata de una generación ‘sin miedo’ respecto a las generaciones anteriores que vivieron la dictadura militar, por lo cual, sienten la obligación, oportunidad y capacidad de transformar la sociedad heredada (Cárdenas, 2014; Cummings, 2015; Sandoval & Carvallo, 2019). Puesto el legado dictatorial como un punto de referencia desde el cual los jóvenes se definen y actúan (Cummings, 2015), esta generación se caracteriza por estar socializada en el neoliberalismo, tocándole vivir la promesa incumplida del modelo de desarrollo, los costos de la modernización neoliberal y la desigualdad engendrada por la concentración económica (Ruiz & Boccardo, 2014; Ruiz & Caviedes, 2020a). De ese modo, ‘los hijos de la modernización neoliberal’, encarnan los conflictos sociopolíticos producidos por la privatización de la vida cotidiana, la desprotección y exclusión social (Ruiz & Caviedes, 2020b), derivando en un descontento puesto en la palestra pública por la brecha entre sus expectativas y la realidad (Cummings, 2015). 

En este contexto de declive de la participación formal y aumento de la participación activista de los jóvenes, investigadores como Somma (2017) plantean que la edad produce una división del trabajo entre votantes y activistas, en donde los mayores se inclinan al voto y los jóvenes a la protesta. Como se dijo, la edad es un factor de desigualdad de voz política y actúa según la forma de participación cívica. Respecto a la participación formal, diversos estudios nacionales evidencian la menor propensión de los jóvenes a participar, siendo la más estudiada la participación electoral (Bargsted et al., 2017; Castillo et al., 2015b; Contreras, Morales & Joignant, 2016; Contreras & Navia, 2013; Corvalan & Cox, 2015; Núñez et al., 2018; PNUD, 2017a; Toro, 2007, 2008). Si bien recientemente se prueba que las nuevas generaciones (nacidas entre 1991 y 1995) están votando más, porque vivieron las movilizaciones estudiantiles del 2006 y 2011 (Bargsted et al., 2019), la tendencia en el tiempo sobre su aumento aún no se comprueba. En cuanto a la participación activista, la literatura nacional muestra un gran acuerdo en que los jóvenes tienen una mayor propensión a participar, por lo general, estudiando la participación en protestas (Bargsted et al., 2017; Castillo et al., 2015b; Ortiz-Inostroza & Lopez, 2017; Roberts, 2016). 

Un resultado robusto en la literatura nacional, es que los factores sociodemográficos de la desigualdad de voz política, también se producen en la población joven del país. En base al mismo modelo de recursos estudiado en población adulta, la evidencia señala que aquellos jóvenes de menos estatus social (medido por los niveles socioeconómicos y educativos de las familias), tienen una menor propensión a la participación formal y activista (Contreras et al., 2016; Contreras & Navia, 2013; Corvalan & Cox, 2015; INJUV, 2017, 2019; Rozas & Somma, 2020; Toro, 2007). Esto plantea desafíos para la legitimidad de la democracia en Chile, puesto que la desigualdad de voz política por estatus social se produce de manera transversal, con independencia del factor etario. No obstante, la participación cívica de los jóvenes es particularmente preocupante, porque sus intereses y expectativas ciudadanas se encuentran doblemente mal representadas por la democracia chilena. A los factores transversales del estatus social, se suma el factor etario de desigualdad de voz política, reflejado en la menor participación formal de los jóvenes. 

Ante la preocupación por la baja participación cívica acumulada de los jóvenes, existe un importante cuerpo de investigación que se pregunta por como se puede promover su participación previamente, a partir del rol de formación ciudadana en las escuelas. La formación ciudadana en el Chile actual, es entendida como un proceso formativo continuo que busca promover no solo el conocimiento cívico, sino también las habilidades y actitudes necesarias para que los estudiantes se desenvuelvan como ciudadanos en una sociedad democrática (Ministerio de Educación [MINEDUC], 2016). Asimismo, la literatura advierte que la formación ciudadana no se acota al currículum formal como mandato explícito hacia las escuelas, en tanto la cultura y el clima escolar pueden influir también en las actitudes, percepciones y creencias de los estudiantes como un currículum oculto (Apple, 1980; González, 2018). En tal sentido, la escuela es concebida como un espacio de socialización política (Cumsille & Martínez, 2015; Deimel et al., 2020; Neundorf et al., 2016), con la posibilidad de promover la participación y solventar la desigualdad política (Bonhomme et al., 2015).

Diversas investigaciones en ciencias sociales se han interesado en probar si la formación ciudadana de las escuelas, como el aprendizaje formal de ciudadanía, el conocimiento cívico, un clima abierto en el aula, las habilidades ciudadanas y la percepción de influencia en las decisiones escolares (i.e., eficacia política en la escuela), promueve la intención de participación formal y activista de los estudiantes (Blaskó et al., 2019; Campbell, 2008; Castillo et al., 2015a; Deimel et al., 2020; Eckstein & Noack, 2016; Hoskins et al., 2017; Isac et al., 2014; Kudrnáč, 2017; Manganelli et al.,, 2015; Miranda, 2018; Neundorf et al., 2016; Quintelier, 2010; Quintelier & Hooghe, 2013; Treviño et al., 2019). Estas intenciones se reportan como la manera más cercana de medir y predecir la participación cívica a futuro, considerando que los estudiantes aún no tienen acceso a todas las formas de participación (Keating & Janmaat, 2016; Quintelier & Blais, 2016; Quintelier & Hooghe, 2013). Por lo cual, se espera que al promover la intención de participación cívica de los estudiantes con la formación ciudadana de las escuelas, se obtengan impactos duraderos en el tiempo (Eckstein & Noack, 2016; Keating & Janmaat, 2016). 

Si bien la socialización política de la escuela a través de la formación ciudadana es algo probado por la literatura, similar a como sucede con la participación cívica en adultos y jóvenes, el modelo de recursos comprueba que aquellos estudiantes de familias con menos estatus social, tienen una menor intención de participación formal y activista (Castillo et al., 2014; Castillo et al., 2015a; Kudrnáč, 2017; Manganelli et al., 2015; Miranda, 2018; Neundorf et al., 2016). En esta línea de investigación, ya no se conceptualiza la preocupación como una desigualdad de voz política, sino más bien, como la transmisión intergeneracional de la desigualdad política (Brady et al., 2015; Miranda, 2018; Schlozman et al., 2012). Este concepto quiere decir que las actitudes, creencias, conocimientos y comportamientos ciudadanos de los estudiantes, tienen una fuerte relación con el estatus social de sus familias (Miranda, 2018). De ese modo, la socialización política de la familia juega un rol importante en la intención de participación cívica de los estudiantes, en paralelo a la socialización política de las escuelas (Neundorf et al., 2016). 

Ante la preocupación por la brecha generada por la transmisión intergeneracional de la desigualdad política, un creciente cuerpo de investigación se aboca a estudiar como es posible mitigar la brecha en la intención de participación cívica de los estudiantes, generadas por el estatus social de las familias (Campbell, 2008; Castillo et al., 2015a; Deimel, et al., 2020; Eckstein & Noack, 2016; Gainous & Martens, 2012; Hoskins et al., 2017; Kudrnáč, 2017; Neundorf et al., 2016). Este vínculo se mitiga cuando la formación ciudadana de las escuelas reduce la brecha por estatus social, pero la literatura sugiere que también puede ser potenciado cuando la formación ciudadana abre aún más la brecha (Campbell, 2008; Deimel et al., 2020; Hoskins et al., 2017). Es decir, mientras que el efecto mitigador se produce cuando los estudiantes desfavorecidos se benefician más de la formación ciudadana, por el contrario, el efecto potenciador es provocado cuando la formación ciudadana beneficia más a los estudiantes privilegiados (Campbell, 2008). 

La evidencia sugiere mitigadores y advierte potenciadores del vínculo entre el estatus social familiar de los estudiantes y la intención de participación cívica, en su mayoría para el caso de la intención de participación formal. Uno de los más estudiados es el clima abierto en el aula, sobre el cual la literatura señala que mitiga la brecha por estatus social (Campbell, 2008; Castillo et al., 2015a; Eckstein & Noack, 2016), mientras que otros estudios indican que la potencia (Gainous & Martens, 2012) o incluso la deja intacta (Deimel et al., 2020; Hoskins et al., 2017; Kudrnáč, 2017). También la literatura prueba el rol de la participación en la escuela, la participación en actividades cívicas y la participación en decisiones escolares, encontrándose evidencia de que mitigan la brecha (Eckstein & Noack, 2016; Gainous & Marten, 2012), aunque otras investigaciones señalan que ni mitigan ni potencian el vínculo entre el estatus social familiar y la intención de participación (Deimel et al., 2020; Hoskins et al., 2017). A pesar de los resultados poco concluyentes, existe un consenso de que el aprendizaje formal de ciudadanía es un mitigador de la brecha por estatus social familiar, lo cual es probado por diversos estudios (Deimel et al., 2020; Gainous & Marten, 2012, Hoskins et al., 2017; Neundorf et al., 2016). 

Siguiendo a Deimel et al. (2020), la evidencia sobre los mitigadores del vínculo entre el estatus social familiar y la intención de participación cívica de los estudiantes es inconsistente, no solo porque los resultados son poco concluyentes y la operacionalización de las variables difieren entre los estudios, sino también por las diferencias en el enfoque analítico adoptado. Mientras que algunos estudios examinan los efectos a nivel individual y escolar (Castillo et al., 2015a; Deimel et al., 2020; Campbell, 2008; Eckstein y Noack, 2016; Kudrnáč, 2017), otras investigaciones los analizan solo a nivel individual (Gainous & Martens,2012; Hoskins et al., 2017; Neundorf et al., 2016). 
