# Sentido de justicia en la escuela

Lo que se espera de las escuelas en las sociedades modernas, es que sean un punto de partida común capaz de corregir las desigualdades de herencia familiar, al brindar oportunidades educativas por igual a todos los estudiantes (Fdez. Enguita, 1990; Peña, 2015; Peña & Toledo, 2017). Sin embargo, la literatura sociológica problematiza este rol, demostrando que las escuelas en muchos casos reproducen el origen en vez de corregirlo (Peña, 2015). Desde las Teorías de la Reproducción Social, la escuela es considerada como un aparato ideológico a cargo de legitimar y ocultar el orden estructural de clases, ante el peso del capital económico, cultural, social y simbólico heredado (Bourdieu & Passeron, 1977). A pesar de esto, Freire (2014) plantea que si se desecha la concepción bancaria de la educación, la escuela puede ser una oportunidad para que los educandos problematicen y reflexionen sobre sus realidades, a modo de que los sometidos luchen por su emancipación. En este sentido, la sociología se pregunta por la justicia en la escuela, a modo de atender como la educación reproduce (o no) las estructuras de desigualdad (Sabbagh & Resh, 2016). 

Walzer (1983) conceptualiza la educación como una esfera de justicia autónoma de otras esferas de la sociedad, con sus propios principios y lógicas de funcionamiento. Un vasto cuerpo de investigaciones en ciencias sociales orienta empíricamente el estudio de la justicia en educación, teniendo como foco de atención las siguientes tres preguntas: 1) ¿qué principios y/o procedimientos se perciben como justos?; 2) ¿cuál es la magnitud percibida de la (in)justicia?; y 3) ¿cuáles son las consecuencias psicológicas y sociales de la (in)justicia? (Sabbagh & Resh, 2016). En este estudio se presta atención a la última pregunta, la cual es contestada en referencia a distintas consecuencias que tiene la justicia en la escuela sobre los estudiantes. En tal sentido, la justicia en la escuela es considerada como parte del currículum oculto (Resh, 2010, 2018; Resh & Sabbagh, 2013, 2014, 2017), el cual como se dijo, puede influir en las actitudes, percepciones y creencias de los estudiantes (Apple, 1980; González, 2018). Los estudios en este campo de investigación se acumulan en la psicología, la psicología social y la pedagogía, y en una menor cantidad se encuentra la literatura sociológica que colabora con la psicología social.  

En cuanto a los aportes de la psicología, la evidencia muestra que la justicia en la escuela tiene efectos positivos sobre la motivación, el aprendizaje, la alegría de aprender y el bienestar académico (Berti, Molinari & Speltini, 2010; Chory-Assad, 2002; Chory-Assad & Paulsen, 2004; Ehrhardt-Madapathi, Pretsch & Schmitt, 2018; Marcin, Morinaj & Hascher, 2019; Peter & Dalbert, 2010), pudiendo contribuir en las emociones positivas y la salud psicológica de los estudiantes (Mameli, Biolcati, Passini & Mancini, 2018). A partir de diversos estudios en psicología social y pedagogía, la literatura señala que la justicia en la escuela tiene un efecto positivo sobre la confianza social por las personas y las instituciones formales, como también en la participación en la escuela y la comunidad (Lenzi et al., 2014; Resh, 2018; Resh & Sabbagh, 2013, 2014). Asimismo, se demostró que promueve la identificación y el sentido de pertenencia a la escuela, fortalece el diálogo y confianza con los profesores, al mismo tiempo que reduce la deslegitimidad, el conflicto y las agresiones hacia ellos (Berti et al., 2010; Chory-Assad, 2002; Chory-Assad & Paulsen, 2004; Čiuladienė & Račelytė, 2016; Gouveia-Pereira, Vala & Correia, 2017; Resh & Sabbagh, 2013).

La contribución de la sociología en colaboraciòn con la psicología social, es un campo de investigación más reducido, pero existe una importante línea de investigación que se orienta al estudio del sentido de justicia en la escuela (Di Battista, Pivetti & Berti, 2014; Gorard, 2011; Jasso & Resh, 2002; Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2010, 2018; Resh & Dalbert, 2007; Resh & Sabbagh, 2009, 2013, 2014, 2016; 2017; Sabbagh & Resh, 2016; Sabbagh et al., 2006). En este cuerpo de investigación, la evidencia empírica tiene en común el abordaje del efecto del género, estatus social de las familias, antecedentes de los estudiantes y tipo de escuela, sobre el sentido de justicia de los estudiantes (Gorard, 2011; Jasso & Resh, 2002; Resh, 2010, 2018; Resh & Dalbert, 2007; Resh & Sabbagh, 2013, 2014, 2017). Un grupo de estudios en esta línea, recientemente se interesa cada vez más en investigar el efecto del sentido de justicia en la escuela sobre la socialización cívica (Resh & Sabbagh, 2016), preocupándose tanto por el comportamiento como las actitudes cívicas de los estudiantes (Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2018; Resh & Sabbagh, 2013, 2014, 2017). El presente estudio se enmarca en este cuerpo de literatura, con el objetivo de analizar el efecto del sentido de justicia en la escuela sobre la intención de participación cívica y probar si mitiga la brecha generada por el estatus social familiar de los estudiantes. 

La evidencia hasta la fecha, aborda superficialmente el efecto de la justicia en la escuela sobre la intención de participación cívica, producto de una operacionalización que se limita a la percepción de los estudiantes sobre la justicia de los profesores (c.f. Eckstein & Noack, 2016). En cambio, la literatura sobre el sentido de justicia en la escuela, brinda aportes conceptuales y empíricos que complejizan dicha operacionalización, al abrirse camino a la justicia distributiva y procesal en la escuela (Chory-Assad, 2002; Chory-Assad & Paulsen, 2004; Čiuladienė & Račelytė, 2016; Gouveia-Pereira et al., 2017; Jasso & Resh, 2002; Resh, 2010, 2018; Resh & Dalbert, 2007; Resh & Sabbagh, 2009; 2013, 2014, 2017; Sabbagh & Resh, 2016; Sabbagh et al., 2006), así como también en otros casos a la justicia interactiva e informativa (Di Battista et al., 2014; Čiuladienė & Račelytė, 2016; Claus et al., 2012; Pretsch & Ehrhardt-Madapathi, 2018).

Dicho lo anterior, en este estudio se consideran dos dimensiones del sentido de justicia en la escuela, las cuales son conceptualizadas como justicia distributiva y justicia relacional (e.g., Čiuladienė & Račelytė, 2016; Claus et al., 2012; Resh, 2010; Resh & Sabbagh, 2013; Sabbagh et al., 2006; Sabbagh & Resh, 2016). En base a estas dimensiones, se sigue la línea de investigación que estudia el efecto del sentido de justicia en la escuela en la socialización cívica de los estudiantes (Resh & Sabbagh, 2016), precisando en el efecto sobre la intención de participación formal y activista. Por lo tanto, en lo que sigue se profundiza sobre qué se entiende por cada una de las dimensiones del sentido de justicia en la escuela, para así abordar sus principales hallazgos, lo estudiado hasta ahora sobre su efecto en la intención de participación cívica de los estudiantes y el efecto mitigador sobre la brecha generada por el estatus social familiar. 

## Justicia distributiva
En el proceso de enseñanza-aprendizaje evaluar el rendimiento de los estudiantes es un momento importante y, por lo general, en la escuela se realiza mediante pruebas estandarizadas (Sabbagh & Resh, 2016). Con estas pruebas se pretende dirimir entre el éxito y el fracaso en la escuela (Tateo, 2018), concibiendo a los estudiantes como individuos autónomos, competitivos y racionales; es decir, como responsables de su éxito y culpables de su fracaso (Dubet, 2011; Tarabini, 2015). Los estudiantes se evalúan de acuerdo a su posición en la distribución de notas, pero al estar regidas las pruebas estandarizadas por la distribución matemática de una Campana de Gauss, por necesidad unos pocos son definidos como sobresalientes, la mayoría como mediocres y otros pocos relegados a la noción de fracasados (Lampert, 2013). Tal forma de las pruebas estandarizadas, esconde que las notas sean una eufemización de clasificaciones sociales y, con resabios del darwinismo social, se sentencia que sólo los mejores son quienes triunfan (Kaplan & Ferrero, 2003). 

Una de las explicaciones de como se preserva la anterior situación, es por la aceptación e importancia que tiene el principio meritocrático en la escuela, en tanto la evidencia señala que la explicación preferida de los estudiantes para el éxito y fracaso, es por su propio esfuerzo y talento (Clycq, Ward Nouwen & Vandenbroucke, 2014; Pansu, Dubois & Dompnier, 2010). Los estudiantes internalizan las notas como valoraciones de sí mismos y explican su desempeño en la escuela por mérito (Lampert, 2013), eximiendo de responsabilidad a otros agentes sociales y a los factores estructurales o adscritos que los caracterizan (Fdez. Enguita, 1990; Peña & Toledo, 2016; Tarabini, 2015). En este sentido, la meritocracia tiene expresión en la escuela con la distribución de notas, lo cual es denominado como justicia distributiva por la línea de investigación que trata el sentido de justicia en la escuela (Chory-Assad, 2002; Chory-Assad & Paulsen, 2004; Jasso & Resh, 2002; Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2010, 2018; Resh & Dalbert, 2007; Resh & Sabbagh, 2009, 2013, 2014, 2017; Sabbagh et al., 2006). 

En la justicia distributiva, los recursos son el esfuerzo y el talento, mientras que las recompensas distribuidas son las notas en las pruebas (Resh, 2010; Resh & Sabbagh, 2013; Sabbagh et al., 2006; Sabbagh & Resh, 2016). Por consiguiente, el sentido de injusticia que emerge de la justicia distributiva, es provocada cuando la comparación entre la nota real y la nota esperada (o merecida), no coincide con las expectativas de los estudiantes (Resh, 2010, 2018; Resh & Sabbagh, 2014, 2017). La literatura señala que la justicia distributiva tiene un carácter instrumental, porque una distribución justa (o injusta) de las notas, afecta la motivación de los estudiantes, sus posibilidades de éxito en la escuela y, en última instancia, sus futuras oportunidades en educación y en la vida (Resh, 2010; Resh & Sabbagh, 2009). De ahí que la distribución de las notas sea un componente integral de la experiencia educativa de los estudiantes (Dalbert, 2004), puesto que además se trata de una recompensa que es valorada e importante para ellos (Resh, 2010; Resh & Dalbert, 2007; Sabbagh & Resh, 2016). 

### Efecto a nivel individual
La literatura sobre la justicia distributiva, señala que la escuela representa un ‘microcosmos’ de la sociedad para los estudiantes, por lo que las experiencias de justicia (o injusticia) distributiva pueden transmitir nociones sobre la sociedad en general (Resh, 2018; Resh & Sabbagh, 2014). Al ser parte del currículum oculto de las escuelas (Resh, 2010, 2018; Resh & Sabbagh, 2013, 2014, 2017), la literatura clásica señala que la percepción justa (o injusta) de como se distribuyen las notas, puede moldear la visión de mundo y el ‘mapa social’ que se construyen los estudiantes (Dreeben 1968; Deutsch 1979 citados en Resh, 2010). Es por esto que, la justicia distributiva en la escuela, transmite mensajes sobre la estructura y procesos sociales de la sociedad, los cuales son componentes básicos de una ciudadanía democrática (Connell, 1993 citado en Resh & Sabbagh, 2014). En este sentido, la justicia distributiva puede ser parte integral de la socialización cívica de los estudiantes y un requisito para el desarrollo de la intención de participación cívica. 

La evidencia empírica que trata la justicia distributiva en la escuela, recientemente investiga su efecto sobre la socialización cívica (Resh & Sabbagh, 2016). Por un lado, respecto al comportamiento cívico se demostró que la justicia distributiva tiene un efecto negativo sobre la deshonestidad académica y la violencia escolar, pero no tuvo efectos significativos sobre la participación en actividades extracurriculares y la participación en voluntariado comunitario (Resh & Sabbagh, 2017). Por otro lado, de acuerdo a las actitudes cívicas se comprueba el efecto positivo sobre la orientación democrática liberal (Resh & Sabbagh, 2014), mientras que Pretsch y Ehrhardt-Madapathi (2018) evidencian un efecto positivo tanto en la aprobación a las derechos humanos y civiles, como en la aprobación a las instituciones democráticas. Si bien estos resultados indican que la justicia distributiva contribuye en las actitudes cívicas de los estudiantes, al mismo tiempo la literatura señala que no tiene efectos significativos sobre la confianza en las instituciones, ni tampoco en la confianza social (Resh & Sabbagh, 2013, 2014). De manera más reciente, Resh (2018) advierte que estos efectos son diferentes de acuerdo al sector del sistema educativo (i.e., para el caso de Israel, depende de si son escuelas de judíos en general, judíos religiosos y árabes).  

Hasta ahora no hay resultados concluyentes acerca de la importancia de la justicia distributiva sobre la socialización cívica de los estudiantes. Tampoco hay estudios dentro del cuerpo de literatura del sentido de justicia en la escuela, en que se analice el efecto de la justicia distributiva sobre la intención de participación cívica de los estudiantes. Sin embargo, debido a la evidencia que respalda la contribución de la justicia distributiva en la promoción de distintos comportamientos y actitudes cívicas deseables (Pretsch & Ehrhardt-Madapathi, 2018; Resh y Sabbagh, 2014, 2017), junto con su imbricación con los componentes básicos de una ciudadanía democrática (Connell, 1993 citado en Resh & Sabbagh, 2014), se espera un efecto positivo sobre la intención de participación formal y activista de los estudiantes. Tal nexo se apoya en que la justicia distributiva como parte del currículum oculto de las escuelas, puede cumplir una función latente en la configuración de las perspectivas sociales y el comportamiento de los estudiantes (Resh, 2010; Resh & Sabbagh, 2009). La evidencia más cercana proviene de la población adulta en Chile, en que se comprueba que las preferencias por la redistribución son un factor relevante que promueve la participación en protestas (Castillo et al., 2015b).

*H1a: la justicia distributiva a nivel individual tendrá un efecto positivo en la intención de participación formal y activista de los estudiantes.*

### Efecto a nivel escolar
La literatura empírica que estudia la justicia distributiva en la escuela, tiene como común denominador considerarla en un nivel individual (c.f. Chory-Assad, 2002; Chory-Assad & Paulsen, 2004; Čiuladienė & Račelytė, 2016; Gorard, 2011; Gouveia-Pereira et al., 2017; Jasso & Resh, 2002; Resh, 2010; Resh & Dalbert, 2007), incluyendo la evidencia que analiza su efecto sobre la socialización cívica de los estudiantes (c.f. Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2018; Resh & Sabbagh, 2013, 2014, 2017). Sin embargo, se propone estudiar también la justicia distributiva a nivel escolar, a modo de explorar entre escuelas el efecto sobre la intención de participación cívica de los estudiantes. Para lo cual, siguiendo la argumentación y la evidencia señalada a nivel individual, se espera que la justicia distributiva tenga un efecto positivo a nivel escolar sobre la intención de participación formal y activista de los estudiantes. 

*H1b: la justicia distributiva a nivel escolar tendrá un efecto positivo en la intención de participación formal y activista de los estudiantes.*

## Justicia relacional
La escuela es un lugar importante en la vida cotidiana de los estudiantes, puesto que pasan gran parte del tiempo en ellas durante su infancia y adolescencia (Resh, 2018). Allí los estudiantes se relacionan diariamente con una diversidad de agentes, tales como compañeros, profesores, directivos, auxiliares, entre otros. No obstante, en particular los profesores son los agentes más importantes y con los cuales más se relacionan los estudiantes. No solo porque tienen la facultad de asignar un recurso valorado como las notas, sino también porque ofrecen elogios, apoyo, ayuda, aliento y estima (Resh, 2018; Resh & Sabbagh, 2009, 2013, 2014, 2016, 2017; Sabbagh & Resh, 2016; Sabbagh et al., 2006), lo cual es apreciado por los estudiantes. Por este motivo, tal como sucede con la justicia distributiva, la justicia que establecen los profesores en las relaciones con sus estudiantes, son un ámbito significativo de sus experiencias escolares (Dalbert, 2004). 

Las relaciones entre profesores y estudiantes no son necesariamente justas, ya que pueden caracterizarse por la distribución desigual del poder que existe en la escuela (Mikula, Petri & Tanzer, 1990 citado en Pretsch & Ehrhardt-Madapathi, 2018). Por lo tanto, diversas investigaciones empíricas se interesan en abordar si los profesores mantienen una relación justa con sus estudiantes, lo que en una importante cantidad de casos se investiga como las relaciones profesor-estudiante en la escuela (e.g., Eckstein & Noack, 2016; Isac et al., 2014; Quintelier & Hooghe, 2013; Treviño et al., 2019). No obstante, el cuerpo de investigación que estudia empíricamente el sentido de justicia en la escuela, conceptualiza la percepción de los estudiantes sobre estas relaciones como justicia relacional (Di Battista et al., 2014; Čiuladienė & Račelytė, 2016; Claus et al., 2012; Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2018; Resh & Sabbagh, 2013, 2014, 2017). Si bien empíricamente ambas líneas de investigación son comparables porque refieren a la misma percepción de justicia en las relaciones de los profesores con sus estudiantes, conceptualmente tienen implicaciones distintas. Mientras que las relaciones profesor-estudiante en la escuela son parte del clima escolar, la justicia relacional es una dimensión del sentido de justicia en la escuela. 
En la literatura que investiga la justicia relacional, no existe consenso sobre si es un aspecto de la justicia distributiva en la escuela, o bien si es un tipo de justicia que desborda lo distributivo. Por un lado, los estudios que consideran la justicia relacional como distributiva, argumentan que los profesores distribuyen el trato justo a sus estudiantes (e.g., Resh, 2018; Resh & Sabbagh, 2013, 2014, 2017). Haciendo el símil con la justicia distributiva, plantean que la justicia relacional en vez de estar guiada por un principio de distribución meritocrático, se rige por un principio de distribución con énfasis en la igualdad (Resh & Sabbagh, 2009, 2013; Sabbagh et al., 2006). Por consiguiente, los estudiantes son tratados como recursos y las recompensas son el trato justo de los estudiantes, en función del comportamiento igualitario de los profesores (Dalbert, 2004; Resh & Sabbagh, 2017). Por otro lado, existen estudios que se refieren a la justicia relacional como una dimensión distinta a la justicia distributiva en la escuela (e.g., Di Battista et al., 2014; Čiuladienė & Račelytė, 2016; Claus et al., 2012; Pretsch & Ehrhardt-Madapathi, 2018). Estos estudios entienden la justicia relacional como la manera en que los profesores se relacionan con sus estudiantes, haciendo alusión a la importancia de que el trato justo en las relaciones interpersonales se base en el respeto, la dignidad y la cortesía (Čiuladienė & Račelytė, 2016; Claus et al., 2012). 

Es cuestionable entender la justicia relacional como distributiva, si los estudiantes son considerados como si fueran recursos y se limita la dimensión subjetiva que implican las relaciones justas entre profesores y estudiantes a una lógica economicista de recompensas (c.f. Dalbert, 2004; Resh & Sabbagh, 2009, 2013, 2017; Sabbagh et al., 2006). Por lo cual, se conceptualiza la justicia relacional como parte de la justicia procesal en la escuela, la cual es definida por el mantenimiento de reglas formales e informales justas aceptadas por todos los estudiantes (Resh & Sabbagh, 2014). En este caso, tal como lo plantea Di Battista et al. (2014), una regla informal que es exigida por todos los estudiantes, es el trato justo interpersonal recibido por los profesores en la escuela. 

### Efecto a nivel individual
Así como la escuela es considerada un espacio de socialización política para los estudiantes (Cumsille & Martínez, 2015; Deimel et al., 2020; Neundorf et al., 2016), existen investigaciones que conciben a los profesores como el principal agente a cargo de llevar a cabo esta socialización (e.g., Sampermans & Claes, 2018). En este sentido, la literatura señala que de los profesores depende el aprendizaje cívico y las competencias cívicas de los estudiantes, sea comprometiéndose con prácticas colaborativas y promovimiento la reconciliación de conflictos (Isac et al., 2014), o si obran en base al respeto, la igualdad y la cortesía (Flanagan, Cumsille, Gill & Gallay, 2007). Por consiguiente, cuando los profesores influyen en los estudiantes en el proceso de enseñanza, no sólo lo hacen a través de los contenidos de sus asignaturas, sino también mediante sus acciones y comportamientos en el aula (Sanderse, 2013 citado en Sampermans & Claes, 2018). De acuerdo a esto, la justicia relacional puede contribuir en la socialización cívica, como también en particular en la intención de participación cívica de los estudiantes. 

La evidencia empírica que trata la justicia relacional en la escuela, recientemente investiga su efecto sobre la socialización cívica (Resh & Sabbagh, 2016). Respecto a los comportamientos cívicos, la evidencia señala que la justicia relacional permite al interior de la escuela disminuir la deshonestidad académica y la violencia escolar, junto con incentivar el voluntariado comunitario de los estudiantes (Resh & Sabbagh, 2017). En cuanto a las actitudes cívicas, se comprueba que la justicia relacional tiene un efecto positivo en la orientación democrática liberal (Resh & Sabbagh, 2014) y en la aprobación a los derechos humanos y civiles, como también en la aprobación a las instituciones democráticas (Pretsch & Ehrhardt-Madapathi, 2018). Asimismo, es un acuerdo de que la justicia relacional promueve en los estudiantes la confianza social y la confianza en las instituciones formales (Resh & Sabbagh, 2013, 2014), en todos los sectores del sistema educativo (i.e., para el caso de Israel, en las escuelas de judíos en general, judíos religiosos y árabes) (Resh, 2018). 

La reciente evidencia sobre la justicia relacional muestra resultados alentadores sobre su contribución en la socialización cívica de los estudiantes. Es de esperarse que la justicia relacional también tenga un efecto positivo sobre la intención de participación cívica de los estudiantes, en cuanto los profesores además de impartir conocimiento, deben ser agentes que inculquen valores, actitudes y normas de comportamiento cívico para que sus estudiantes participen como ciudadanos comprometidos en el futuro (Resh, 2018). Al ser vistos los profesores como modelos a seguir (Sampermans & Claes, 2018), el trato justo que establezcan en las relaciones con sus estudiantes, puede mejorar la aprobación y el compromiso de los estudiantes con las prácticas democráticas (Flanagan et al., 2007). En línea con tal argumento, Lenzi et al. (2014) desde la psicología comunitaria, explican que el trato justo de los profesores fortalece el desarrollo de un sistema de creencias en los estudiantes en que se valora la igualdad, la equidad y los objetivos colectivos. Por consiguiente, plantean que tal sistema de creencias orientado al bien común, puede contribuir en las intenciones de participar de los estudiantes en el futuro.

Hasta la fecha la literatura empírica sobre el sentido de justicia en la escuela, aún no analiza el efecto de la justicia relacional sobre la intención de participación formal y activista de los estudiantes. No obstante, la evidencia acumulada sobre las relaciones profesor-estudiante en la escuela permite orientar tal efecto a nivel individual (e.g., Eckstein & Noack, 2016; Quintelier & Hooghe, 2013), pues como se dijo, esta línea de investigación es empíricamente comparable al cuerpo de literatura que estudia la justicia relacional. 

La literatura internacional considerando múltiples países, indica que las relaciones profesor-estudiante en la escuela a nivel individual tienen un efecto positivo sobre la intención de participación política electoral, pero un efecto negativo en la intención de participación en protestas legales de los estudiantes (Quintelier & Hooghe, 2013). Por su parte, una investigación en Alemania demuestra un efecto negativo a nivel individual de la justicia de los profesores sobre las intenciones de participación política (Eckstein & Noack, 2016). En este estudio se considera la intención de participación cívica de los estudiantes como un misceláneo de diversas formas de participación, lo que se demuestra en un alfa de cronbach bastante bajo ($\alpha$ = .55). Por lo tanto, en general la evidencia sobre las relaciones profesor-estudiante en la escuela muestra resultados poco concluyentes, pues las formas de medir la intención de participación cívica son distintas entre los estudios. Además, en la literatura revisada no se encuentra evidencia del efecto a nivel individual para el caso específico de Chile. 

A pesar de la escasa evidencia y el problema que agrega que sean estudios con tipologías distintas, la literatura sobre las relaciones profesor-estudiante basadas en el trato justo, ayuda a orientar el sentido de la relación de la justicia relacional a nivel individual sobre la intención de participación formal y activista de los estudiantes. Ponderando los argumentos que señalan la contribución del trato justo de los profesores a la intención de participación cívica (Flanagan et al., 2007; Lenzi et al., 2014) y la evidencia empírica que brinda la literatura internacional, se espera que la justicia relacional tenga un efecto positivo a nivel individual sobre la intención de participación formal y activista de los estudiantes. En tal sentido, no hay suficiente evidencia empírica ni una explicación teórica para sostener un sentido de la relación distinto para la intención de participación activista de los estudiantes, tal como sugieren los resultados de Quintelier y Hooghe (2013). 

*H2a: la justicia relacional a nivel individual tendrá un efecto positivo en la intención de participación formal y activista de los estudiantes.*

### Efecto a nivel escolar
Las investigaciones empíricas que estudian el efecto de la justicia relacional sobre la socialización cívica de los estudiantes, consideran esta dimensión del sentido de justicia en la escuela siempre a un nivel individual (c.f. Pretsch & Ehrhardt-Madapathi, 2018; Resh, 2018; Resh & Sabbagh, 2013, 2014, 2017). No obstante, la línea de investigación que estudia el trato justo en las relaciones profesor-estudiante en paralelo a la justicia relacional, por lo general concibe estas relaciones como parte del clima escolar (e.g., Eckstein & Noack, 2016; Isac et al., 2014; Quintelier & Hooghe, 2013). Por lo cual, por antonomasia se infiere que las relaciones justas que establecen los profesores, son comprendidas por estas investigaciones como una percepción general que realizan los estudiantes sobre su escuela. Dicho de otro modo, la justicia relacional puede ser considerada una evaluación general hacia los profesores en la escuela, a pesar de que sea reportado a nivel individual por los estudiantes. 

La literatura sobre el sentido de justicia en la escuela, hasta ahora no ha estudiado el efecto de la justicia relacional a nivel escolar sobre la intención de participación formal y activista de los estudiantes, pero existe una vasta evidencia en paralelo sobre el trato justo en las relaciones profesor-estudiante. Por un lado, la literatura internacional considerando una cantidad importante de países, prueba un efecto positivo a nivel escolar de las relaciones profesor-estudiante en la escuela sobre la ciudadanía convencional (Isac et al., 2014), aunque otro estudio de la misma categoría no encontró un efecto positivo sobre las intenciones de participación electoral de los estudiantes (Quintelier & Hooghe, 2013). Por otro lado, la anterior literatura internacional mantiene un consenso sobre el efecto positivo a nivel escolar de las relaciones profesor-estudiantes sobre la ciudadanía relacionada con los movimientos sociales (Isac et al., 2014) o la intención de participar en protestas legales (Quintelier & Hooghe, 2013). La evidencia para el caso de Chile, corrobora el efecto positivo a nivel escolar de las relaciones profesor-estudiantes en las expectativas de participación electoral y las expectativas de participar en protestas legales (Treviño et al., 2019). 

Si bien se mantiene el problema de que la evidencia conceptualiza de diversas maneras la intención de participación cívica de los estudiantes, la literatura sobre las relaciones profesor-estudiante en la escuela permite dirimir el sentido de la relación a nivel escolar de la justicia relacional. La evidencia es suficiente para sostener que la justicia relacional a nivel escolar, tendrá un efecto positivo sobre la intención de participación formal y activista de los estudiantes. Aquello se encuentra en coincidencia con la explicación desarrollada por Flanagan et al. (2007) y Lenzi et al. (2014) para tal efecto a nivel individual, junto con la evidencia empírica reciente sobre el caso de Chile por Treviño et al. (2019). 

*H2b: la justicia relacional a nivel escolar tendrá un efecto positivo en la intención de participación formal y activista de los estudiantes.*

## Efecto mitigador de la justicia distributiva y relacional
La literatura internacional y nacional es consistente al probar con el modelo de recursos, la brecha generada por el estatus social de las familias en la intención de participación cívica de los estudiantes (Castillo et al., 2014; Castillo et al., 2015a; Kudrnáč, 2017; Manganelli et al., 2015; Miranda, 2018; Neundorf et al., 2016). Esto que es conceptualizado como la transmisión intergeneracional de la desigualdad política (Brady et al., 2015; Miranda, 2018; Schlozman et al., 2012), para una creciente área de investigación es un desafío y preocupación identificar como mitigar la brecha (Campbell, 2008; Castillo et al., 2015a; Deimel, et al., 2020; Eckstein & Noack, 2016; Gainous & Martens, 2012; Hoskins et al., 2017; Kudrnáč, 2017; Neundorf et al., 2016). En este sentido, interesa probar si la justicia distributiva y relacional en la escuela, logran mitigar el vínculo entre el estatus social familiar y la intención de participación formal y activista de los estudiantes. De acuerdo a lo planteado por Deimel et al. (2020), el efecto mitigador de ambas dimensiones del sentido de justicia en la escuela solo será analizado a nivel individual. 

La literatura empírica que investiga la justicia distributiva, hasta ahora no ha probado si mitiga la brecha generada generada por el estatus social familiar, pero existe evidencia complementaria que alienta su estudio. La evidencia disponible señala que los niveles de justicia distributiva en la escuela, no están significativamente afectados por el estatus social de sus familias (Resh, 2010; Resh & Dalbert, 2007). Esto es un aspecto a favor si logra mitigar el vínculo entre el estatus social familiar y la intención de participación cívica de los estudiantes, puesto que otros mitigadores ya probados sobre este vínculo, tales como un clima abierto en el aula, la participación en actividades cívicas y la educación formal en ciudadanía, se caracterizan por su desigualdad de acceso (Deimel et al., 2020; Hoskins et al., 2017). Este acceso desigualdad refiere a las barreras que obstaculizan a los estudiantes más desfavorecidos beneficiarse de la formación ciudadana, exacerbando la desigualdad al proporcionar más preparación a aquellos que ya es probable que alcancen una cantidad suficiente de voz política (Kahne & Middaugh, 2008 citado en Deimel et al., 2020). Al carecer la justicia distributiva de esta desigualdad de acceso, puede ser valioso su aporte como parte del currículum oculto en la escuela, para mitigar a nivel individual el vínculo entre el estatus social familiar y la intención de participación formal y activista de los estudiantes. 

*H3a: la justicia distributiva a nivel individual logrará mitigar el vínculo entre el estatus social familiar y la intención de participación formal y activista de los estudiantes.*

Para el caso de la justicia relacional, la literatura empírica tampoco investiga si mitiga el vínculo entre el estatus social de las familias y la intención de participación cívica. No obstante, en paralelo la literatura sobre las relaciones profesor-estudiante basadas en el trato justo, muestra resultados alentadores sobre el efecto mitigador que pueda tener la justicia relacional. Al respecto, las relaciones profesor-estudiante en la escuela en múltiples países de Europa, han logrado mitigar la brecha de género en las actitudes hacia la igualdad de género (Sampermans & Claes, 2018), como también la brecha por estatus social en el caso de la participación social de los estudiantes (Wanders, Dijkstra, Maslowski & van der Veen, 2020; Wanders, van der Veen, Dijkstra & Maslowski, 2020). La evidencia internacional más cercana la brindan Eckstein y Noack (2016), al probar que la justicia de los profesores en la escuela mitiga la brecha generada por el estatus social de las familias, en la intención de participación política de los estudiantes. A pesar de la limitación de que este estudio no diferencia entre la intención de participación formal y activista, junto con la falta de evidencia para el caso de Chile, es de esperar que la justicia relacional logre mitigar a nivel individual la brecha generada por el estatus social familiar.

*H3b: la justicia relacional a nivel individual logrará mitigar el vínculo entre el estatus social familiar y la intención de participación formal y activista de los estudiantes.*

