# Bibliografía {-}

Apple, M. (1980). The other side of the hidden curriculum: correspondence theories and the labor process. The Journal of Education, 162(1), 47–66. Recuperado de http://www.jstor.org/stable/42741975

Arias-Cardona, A. M. & Alvarado, S. V. (2015). Jóvenes y política: de la participación formal a la movilización informal. Revista Latinoamericana de Ciencias Sociales, Niñez y Juventud, 13(2), 581–594. doi: 10.11600/1692715x.1322241014 

Bargsted, M. & Maldonado, L. (2018). Party identification in an encapsulated party system: The case of postauthoritarian Chile. Journal of Politics in Latin America, 10(1), 29–68. doi: https://doi.org/10.1177/1866802X1801000102 

Bargsted, M., Somma, N., Campos, T. & Joignant, A. (2017). Ciudadanía y democracia: desigualdades de voz política. Notas COES de Política Pública, 11, 1–17. doi: 10.13140 / RG.2.2.28798.28480 

Bargsted, M., Somma, N. & Muñoz-Rojas, B. (2019). Participación electoral en Chile. Una aproximación de edad, período y cohorte. Revista de ciencia política, 39(1), 75–98. doi: http://dx.doi.org/10.4067/S0718-090X2019000100075 

Berti, C., Molinari, L. & Speltini, G. (2010). Classroom justice and psychological engagement: students’ and teachers’ representations. Social Psychology of Education, 13(4), 541–556. doi: https://doi.org/10.1007/s11218-010-9128-9 

Bidegain, G. (2015). Autonomización de los movimientos sociales e intensificación de la protesta: estudiantes y mapuches en Chile (1990–2013) (Tesis de doctorado). Pontificia Universidad Católica de Chile, Santiago de Chile.

Blaskó, Z., Dinis da Costa, P. & Vera-Toscano, E. (2019). Non-cognitive civic outcomes: How can education contribute? European evidence from the ICCS 2016 study. International Journal of Educational Research, 98, 366–378. doi: https://doi.org/10.1016/j.ijer.2019.07.005 

Bonhomme, M., Cox, C., Tham, M. & Lira, R. (2015). La educación ciudadana escolar de Chile ‘en acto’: prácticas docentes y expectativas de participación política de estudiantes. En C. Cox & J. C. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados (pp. 373–425). Santiago de Chile: Ediciones Universidad Católica de Chile.

Bourdieu, P. & Passeron, J. C. (1977). La reproducción. Elementos para una teoría del sistema de enseñanza. Barcelona: Laia.

Brady, H. E., Schlozman, K. L. & Verba, S. (2015). Political Mobility and Political Reproduction from Generation to Generation. The ANNALS of the American Academy of Political and Social Science, 657(1), 149–173. doi: https://doi.org/10.1177/0002716214550587 

Brady H, E., Verba, S. & Schlozman K. L. (1995). Beyond SES: a resource model of political participation. American Political Science Review, 89(2), 271–294. doi: 10.2307/2082425

Campbell, D. E. (2008). Voice in the Classroom: How an Open Classroom Climate Fosters Political Engagement Among Adolescents. Political Behavior, 30, 437–454. doi: https://doi.org/10.1007/s11109-008-9063-z 

Carlin, R. (2006). The decline of citizen participation in electoral politics in post-authoritarian Chile. Democratization, 13(4), 632–651. doi: https://doi.org/10.1080/13510340600791921 

Castiglioni, R. & Rovira, C. (2016). Challenges to political representation in contemporary Chile. Journal of Politics in Latin America, 8(3), 3–24. doi: https://doi.org/10.1177/1866802X1600800301 

Castillo, J. C., Miranda, D., Bonhomme, M., Cox, C. & Bascopé, M. (2014). Social inequality and changes in students’ expected political participation in Chile. Education, Citizenship and Social Justice, 9(2), 140–156. doi: https://doi.org/10.1177/1746197914520650 

Castillo, J. C., Miranda, D., Bonhomme, M., Cox, C. & Bascopé, M. (2015a). Mitigating the political participation gap from the school: the roles of civic knowledge and classroom climate. Journal of Youth Studies, 18(1), 16–35. doi: https://doi.org/10.1080/13676261.2014.933199 

Castillo, J. C., Palacios, D. Joignant, A. & Tham, M. (2015b). Inequality, Distributive Justice and Political Participation: An Analysis of the Case of Chile. Bulletin of Latin American Research, 34(4), 486–502. doi: https://doi.org/10.1111/blar.12369 

Chory-Assad, R. (2002). Classroom justice: Perceptions of fairness as a predictor of student motivation, learning, and aggression. Communication Quarterly, 50(1), 58–77. doi: https://doi.org/10.1080/01463370209385646 

Chory‐Assad, R. & Paulsel, M. (2004) Classroom justice: student aggression and resistance as reactions to perceived unfairness. Communication Education, 53(3), 253–273. doi: https://doi.org/10.1080/0363452042000265189 

Čiuladienė, G. & Račelytė, D. (2016). Perceived unfairness in teacher-student conflict situations: students’ point of view. Polish Journal of Applied Psychology, 14(1), 49–66. doi: 10.1515/pjap-2015-0049

Claus, C., Chory, R. & Malachowski, C. (2012). Student Antisocial Compliance-Gaining as a Function of Instructor Aggressive Communication and Classroom Justice. Communication Education, 61(1), 17–43. doi: https://doi.org/10.1080/03634523.2011.619270 

Clycq, N., Ward Nouwen, M. A. & Vandenbroucke, A. (2014). Meritocracy, deficit thinking and the invisibility of the system: Discourses on educational success and failure. British Educational Research Journal, 40(5), 796–819. doi: https://doi.org/10.1002/berj.3109 

Contreras, G., Morales, M. & Joignant, A. (2016). The Return of Censitary Suffrage? The Effects of Automatic Voter Registration and Voluntary Voting in Chile. Democratization, 23(3), 520–544. doi: https://doi.org/10.1080/13510347.2014.986720 

Contreras, G. & Navia, P. (2013). Diferencias generacionales en la participación electoral en Chile, 1988-2010. Revista de ciencia política, 33(2), 419–441. doi: http://dx.doi.org/10.4067/S0718-090X2013000200001 

Corvalán, A. & Cox, P. (2015). Participación y desigualdad electoral en Chile. En C. Cox & J. C. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados (pp. 175–206). Santiago de Chile: Ediciones Universidad Católica de Chile.

Cummings, P. (2015). Democracy and Student Discontent: Chilean Student Protest in the Post-Pinochet Era. Journal of Politics in Latin America, 7(3), 49–84. doi: https://doi.org/10.1177/1866802X1500700302 

Cumsille, P. & Martínez, M. L. (2015). La escuela como contexto de socialización política: Influencias colectivas e individuales. En C. Cox & J. C. Castillo (Eds.), Aprendizaje de la Ciudadanía: Contextos, Experiencias y Aprendizajes (pp. 431–457). Santiago de Chile: Ediciones Universidad Católica de Chile. 

Dalbert, C. (2004). The implications and functions of just and unjust experiences in school. En C. Dalbert & H. Sallay (Eds.), The justice motive in adolescence and young adulthood (pp. 117–134). New York: Routledge. doi: https://doi.org/10.4324/9780203575802 

Dalton, R. (2017). The participation gap. Social status and political inequality. Oxford University Press. doi: 10.1093/oso/9780198733607.001.0001 

Dalton, R. (2008). Citizenship norms and the expansion of political participation. Political Studies, 56(1), 76–98. doi: https://doi.org/10.1111/j.1467-9248.2007.00718.x

Dalton, R. (2006). Citizen Politics. Public opinion and political parties in advanced industrial democracies. Washington D.C: CQ Press.

Dalton, R. J. & Klingemann, H. D. (2007). Citizens and Political Behavior. En R. J. Dalton & H. D. Klingemann (Eds.), The Oxford Handbook of Political Behavior (pp. 3–26). New York: Oxford University Press. doi: 10.1093/oxfordhb/9780199270125.001.0001

Dalton, R., van Sickle, A. & Weldon, S. (2010). The individual–institutional nexus of protest behaviour. British Journal of Political Science, 40(1), 51–73. doi: https://doi.org/10.1017/S000712340999038X 

Deimel, D., Hoskins, B. & Abs, H. J. (2020). How do schools affect inequalities in political participation: compensation of social disadvantage or provision of differential access? Educational Psychology, 40(2), 146–166. doi: https://doi.org/10.1080/01443410.2019.1645305 

Delamaza, G. (2010). La disputa por la participación en la democracia elitista chilena. Latin American Research Review, 45(4), 274–297. doi: https://doi.org/10.1353/lar.2010.0038  

Della Porta, D. (2013). Can Democracy Be Saved: Participation, Deliberation and Social Movements. Cambridge: Polity.

Di Battista, S., Pivetti, M. & Berti, C. (2014). Engagement in the university context: exploring the role of a sense of justice and social identification. Social Psychology of Education, 17(3), 471–490. doi: https://doi.org/10.1007/s11218-014-9255-9 

Donoso, S. & von Bülow, M. (Eds.) (2017). Social Movements in Chile. Organization, trajectories & political consequences. Nueva York: Palgrave Macmillan. doi: 10.1057/978-1-137-60013-4 

Dubet, F. (2011). Egalité des places, égalité des chances. Études, 414(1), 31–41. Recuperado de https://www.cairn.info/revue-etudes-2011-1-page-31.htm# 

Dubrow, J. K., Slomczynski, K. M. & Tomescu-Dubrow, I. (2008). Effects of democracy and inequality on soft political protest in Europe: Exploring the European social survey data. International Journal of Sociology, 38(3), 36–51. doi: https://doi.org/10.2753/IJS0020-7659380302 

Eckstein, K. & Noack, P. (2016). Classroom climate effects on adolescents’ orientations toward political behaviors: a multilevel approach. En P. Thijssen, J. Siongers, J. van Laer, J. Haers & S. Mels (Eds.), Political engagement of the young in Europe: Youth in the crucible (pp. 161–177). London: Routledge.

Ehrhardt-Madapathi, N., Pretsch, J. & Schmitt, M. (2018). Effects of Injustice in Primary Schools on Students' Behavior and Joy of Learning. Social Psychology of Education, 21(2), 337–369. doi: https://doi.org/10.1007/s11218-017-9416-8 

Ekman, J. & Amnå, E. (2012). Political participation and civic engagement: Towards a new typology. Human Affairs, 22(3), 283–300. doi: https://doi.org/10.2478/s13374-012-0024-1 

Escobar, S. (2019). Participación juvenil: descripciones e interrogantes desde los resultados de la IX Encuesta Nacional de Juventud. Revista RT, 8, 7–13. Recuperado de http://www.injuv.gob.cl/storage/docs/RT_31_WEB.pdf 

Fdez. Enguita, M. (1990). La escuela a examen (Un análisis sociológico para educadores y otras personas interesadas). Madrid: Universidad Complutense.

Finch, W. H., Bolin, J. E. & Kelley, K. (2014). Multilevel Modeling Using R. New York: Chapman and Hall/CRC. Recuperado de https://juancarloscastillo.github.io/jc-castillo/documents/diplomado_multinivel/bibliografia/finch%20et%20al%202014%20multilevel%20modeling%20using%20R.pdf 

Flanagan, C. (2016). Epilogue. Youth and the ‘social contract’. En P. Thijssen, J. Siongers, J. van Laer, J. Haers & S. Mels (Eds.), Political engagement of the young in Europe: Youth in the crucible (pp. 195–203). London: Routledge.

Flanagan, C. (2013) Teenage Citizens: The Political Theories of the Young. Cambridge: Harvard University Press.

Flanagan, C. A., Cumsille, P., Gill, S. & Gallay, L. S. (2007). School and community climates and civic commitments: Processes for ethnic minority and majority students. Journal of Educational Psychology, 99(2), 421–431. doi: https://doi.org/10.1037/0022-0663.99.2.421 

Flanagan, C. & Sherrod, L. (1998). Youth political development: An introduction. Journal of Social Issues, 54(3), 447–456. doi: https://doi.org/10.1111/j.1540-4560.1998.tb01229.x 

Flores, I., Sanhueza, C., Atria, J. & Mayer, R. (2019). Top Incomes in Chile: A Historical Perspective on Income Inequality, 1964-2017. Review of Income and Wealth, (solo en línea). doi: https://doi.org/10.1111/roiw.12441  

Freire, P. (2014). Pedagogía del Oprimido. Buenos Aires: Siglo XXI Editores Argentina.

Gainous, J. & Martens, A. M. (2012). The effectiveness of civic education: Are “good” teachers actually good for “all” students? American Politics Research, 40(2), 232–266. doi: https://doi.org/10.1177/1532673X11419492 

Garretón, M. A. (2016). La ruptura entre política y sociedad. Una introducción. En M. A. Garretón (Ed.), La gran ruptura. Institucionalidad política y actores sociales en el Chile del siglo XXI (pp. 11–20). Santiago de Chile: LOM Ediciones. 

Garretón, M. A. & Garretón, R. (2010). La democracia incompleta en Chile: La realidad tras los rankings internacionales. Revista de ciencia política, 30(1), 115–148. doi: http://dx.doi.org/10.4067/S0718-090X2010000100007 

Garretón, M. A., Joignant, A., Somma, N. & Campos, T. (Eds.) (2017). Conflicto Social en Chile 2015- 2016: disputando mitos. Santiago de Chile: Centro de Estudios de Conflictos y Cohesión Social. Recuperado de https://coes.cl/publicaciones/n4-conflicto-social-en-chile-2015-2016-disputando-mitos/

González, C. (2018). Cultura cívica escolar: propuesta de modelo conceptual para el estudio de formación ciudadana en espacios escolares (Tesis de magíster). Pontificia Universidad Católica de Chile, Santiago de Chile. Recuperado de https://repositorio.uc.cl/handle/11534/22253 

Gorard, S. (2011). The potential determinants of young people's sense of justice: an international study. British Journal of Sociology of Education, 32(1), 35–52. doi: https://doi.org/10.1080/01425692.2011.527721 

Gouveia‐Pereira, M., Vala, J. & Correia, I. (2017). Teachers' legitimacy: Effects of justice perception and social comparison processes. British Journal of Educational Psychology, 87(1), 1–15. doi: https://doi.org/10.1111/bjep.12131 

Hess, D. & McAvoy, P. (2015). The political classroom: Evidence and ethics in democratic education. New York: Routledge.

Hoskins, B., Janmaat, J. G. & Melis, G. (2017). Tackling inequalities in political socialisation: A systematic analysis of access to and mitigation effects of learning citizenship at school. Social Science Research, 68, 88–101. doi: https://doi.org/10.1016/j.ssresearch.2017.09.001 

Hox, J. (2010). Multilevel analysis: Techniques and applications. New York: Routledge. Recuperado de https://faculty.psau.edu.sa/filedownload/doc-12-pdf-7a03db1c2b00f1fac2f67c8e4e57414b-original.pdf 

Instituto Nacional de la Juventud (INJUV). (2019). Desarrollo Cívico/Social. En INJUV, 9na Encuesta Nacional de Juventud (pp. 56–85). Santiago de Chile: Ministerio de Desarrollo Social y Familia. Recuperado de http://www.injuv.gob.cl/noticias/9encuesta

Instituto Nacional de la Juventud (INJUV). (2017). Democracia y Participación Sociopolítica de las Juventudes. En INJUV, 8va Encuesta Nacional de Juventud (pp. 66–93). Santiago de Chile: Ministerio de Desarrollo Social. Recuperado de http://www.injuv.gob.cl/storage/docs/Libro_Octava_Encuesta_Nacional_de_Juventud.pdf 

Isac, M, Maslowski, R. Creemers, B. & van der Werf, G. (2014). The contribution of schooling to secondary-school students' citizenship outcomes across countries. School Effectiveness and School Improvement, 25(1), 29–63. doi: https://doi.org/10.1080/09243453.2012.751035 

Jasso, G. & Resh, N. (2002). Exploring the Sense of Justice about Grades. European Sociological Review, 18(3), 333–351. doi: https://doi.org/10.1093/esr/18.3.333 

Kaplan, C. V. & Ferrero, F. (2003). Los ganadores y los perdedores. Un examen de la noción de talentos naturales asociada con el éxito o fracaso escolar. Educación, lenguaje y sociedad, 1(1), 121–136. Recuperado de http://www.biblioteca.unlpam.edu.ar/pubpdf/ieles/n01a08kaplan.pdf 

Keating, A. & Janmaat, J. G. (2016). Education through citizenship at school: Do school activities have a lasting impact on youth political engagement? Parliamentary Affairs, 69(2), 409–429. doi: https://doi.org/10.1093/pa/gsv017 

Kudrnáč, A. (2017). Vliv klimatu školní třídy a jejího socioekonomického složení na občanské znalosti a postoj k volební účasti. Sociologický časopis, 53(2), 209–240. doi: https://doi.org/10.13060/00380288.2017.53.2.314 

Lampert, K. (2013). Meritocratic education and social worthlessness. New York: Palgrave Pivot. doi: https://doi.org/10.1057/9781137324894 

Lijphart, A. (1997). Unequal participation: democracy’s unresolved dilemma. American Political Science Review, 91(1), 1–14. doi: 10.2307 / 2952255 

Lechner, N. (1994). Chile 2000: Las sombras del mañana. Estudios Internacionales, 27(105), 3-11. doi: 10.5354/0719-3769.2011.15352 

Lenzi, M., Vieno, A., Sharkey, J., Mayworm, A., Scacchi, L., Pastore, M. & Santinello, M. (2014). How School can Teach Civic Engagement Besides Civic Education: The Role of Democratic School Climate. American Journal of Community Psychology, 54, 251–261. doi: https://doi.org/10.1007/s10464-014-9669-8 

Luna, J. P. (2016). Delegative democracy revisited. Chile’s crisis of representation. Journal of Democracy, 27(3), 129–138. doi: https://doi.org/10.1353/jod.2016.0046

Mameli, C., Biolcati, R., Passini, S. & Mancini, G. (2018). School context and subjective distress: The influence of teacher justice and school-specific well-being on adolescents’ psychological health. School Psychology International, 39(5), 526–542. doi: https://doi.org/10.1177/0143034318794226 

Manganelli, S., Lucidi, F. & Alivernini, F. (2015). Italian adolescents' civic engagement and open classroom climate: The mediating role of self-efficacy. Journal of Applied Developmental Psychology, 41, 8–18. doi: https://doi.org/10.1016/j.appdev.2015.07.001 

Marcin, K., Morinaj, J. & Hascher, T. (2019). The Relationship between Alienation from Learning and Student Needs in Swiss Primary and Secondary Schools. Zeitschrift für Pädagogische Psychologie, 34(1), 35–49. doi: https://doi.org/10.1024/1010-0652/a000249

Marien, S., Hooghe, M. & Quintelier, E. (2010). Inequalities in non-institutionalised forms Of political participation: A multi-level analysis of 25 countries. Political Studies, 58(1), 187–213. doi: https://doi.org/10.1111/j.1467-9248.2009.00801.x 

Medel, R. & Somma, N. (2016). ¿Marchas, ocupaciones o barricadas? Explorando los determinantes de las tácticas de la protesta en Chile. Política y gobierno, 23(1), 163–199. Recuperado de http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1665-20372016000100163 

Ministerio de Educación (MINEDUC), División de Educación General. (2016). Orientaciones para la elaboración del Plan de Formación Ciudadana. Recuperado de http://formacionciudadana.mineduc.cl/wp-content/uploads/sites/46/2016/04/DEG-OrientacionesPFC-intervenible-AReader_FINAL.pdf 

Miranda, D. (2018). Desigualdad y ciudadanía: una aproximación intergeneracional (Tesis de doctorado). Pontificia Universidad Católica de Chile, Santiago de Chile. Recuperado de https://repositorio.uc.cl/handle/11534/22255 

Miranda, D., Castillo, J. C. & Sandoval-Hernandez, A. (2017). Young Citizens Participation: Empirical Testing of a Conceptual Model. Youth & Society, 52(2), 251–271. doi: https://doi.org/10.1177/0044118X17741024 

Mizala, A., & Torche, F. (2012). Bringing the schools back in: the stratification of educational achievement in the Chilean voucher system. International Journal of Educational Development, 32(1), 132–144. doi: https://doi.org/10.1016/j.ijedudev.2010.09.004 

Navia, P. (2004). Participación electoral en Chile, 1988-2001. Revista de ciencia política, 24(1), 81-103. doi: http://dx.doi.org/10.4067/S0718-090X2004000100004 

Neundorf, A., Niemi, R. G. & Smets, K. (2016). The compensation effect of civic education on political engagement: How civics classes make up for missing parental socialization. Political Behavior, 38(4), 921–949. doi: https://doi.org/10.1007/s11109-016-9341-0 

Neundorf, A. & Smets, K. (2017). Political socialization and the making of citizens. Oxford Handbooks Online. doi:10.1093/oxfordhb/9780199935307.013.98 

Núñez, C., Osorio, R. & Peit, M. (2018). ¿Empoderamiento ciudadano? Evolución y determinantes de la participación y la politización en Chile, 1990-2016. En C. Berríos & C. García (Eds.), Ciudadanías en conflictos. Enfoques, experiencias y propuestas (pp. 223–259). Santiago de Chile: Ariadna Ediciones. Recuperado de https://books.openedition.org/ariadnaediciones/1214?lang=es 

Ortiz-Inostroza, C. & Lopez, E. (2017). Explorando modelos estadísticos para explicar la participación en protestas en Chile. Revista de Sociología 32(1), 13–31. doi: 10.5354/0719-529x.2017.47883

Pansu, P., Dubois, N. & Dompnier, B. (2008). Internality-norm theory in educational contexts. European Journal of Psychology of Education, 23(4), 385–397. doi: https://doi.org/10.1007/BF03172748 

Parker, C. (2000). Los jóvenes chilenos. Cambios culturales, perspectivas del siglo XXI. Santiago de Chile: Mideplan. Recuperado de https://www.academia.edu/13187022/Los_j%C3%B3venes_chilenos_cambios_culturales_perspectivas_para_el_siglo_XXI 

Peña, C. (2015). Escuela y vida cívica. En C. Cox & J. C. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados (pp. 27–49). Santiago de Chile: Ediciones Universidad Católica de Chile. 

Peña, M. & Toledo, C. (2016). Discursos sobre clase social y meritocracia de escolares vulnerables en Chile. Cadernos de Pesquisa, 47(164), 496–518. doi: https://doi.org/10.1590/198053143752 

Peter, F. & Dalbert, C. (2010). Do my teachers treat me justly? Implications of students’ justice experience for class climate experience. Contemporary Educational Psychology, 35(4), 297–305. doi: https://doi.org/10.1016/j.cedpsych.2010.06.001 

Pretsch, J. & Ehrhardt-Madapathi, N. (2018). Experiences of justice in school and attitudes towards democracy: A matter of social exchange? Social Psychology of Education, 21(1), 655–675. doi: https://doi.org/10.1007/s11218-018-9435-0 

Programa de las Naciones Unidas para el Desarrollo (PNUD). (2019). Diez años de auditoría a la democracia: Antes del estallido. Santiago de Chile: Programa de las Naciones Unidas para el Desarrollo. Recuperado de https://www.cl.undp.org/content/chile/es/home/library/diez-anos-de-auditoria-a-la-democracia--antes-del-estallido.html 

Programa de las Naciones Unidas para el Desarrollo (PNUD). (2017a). Diagnóstico sobre la participación electoral en Chile. Santiago de Chile: Programa de las Naciones Unidas para el Desarrollo. Recuperado de https://www.cl.undp.org/content/chile/es/home/library/democratic_governance/diagnostico-sobre-la-participacion-electoral-en-chile.html 

Programa de las Naciones Unidas para el Desarrollo (PNUD). (2017b). Desiguales: Orígenes, cambios y desafíos de la brecha social en Chile. Santiago de Chile: Programa de Naciones Unidas para el Desarrollo. Recuperado de https://www.cl.undp.org/content/chile/es/home/library/poverty/desiguales--origenes--cambios-y-desafios-de-la-brecha-social-en-.html 

Programa de las Naciones Unidas para el Desarrollo (PNUD). (2015). Informe sobre Desarrollo Humano en Chile 2015. Los tiempos de la politización. Santiago de Chile: Programa de Naciones Unidas para el Desarrollo. Recuperado de https://www.cl.undp.org/content/chile/es/home/library/human_development/los-tiempos-de-la-politizacion.html 

Quintelier, E. (2010). The effect of schools on political participation: A multilevel logistic analysis. Research Papers in Education, 25(2), 137–154. doi: https://doi.org/10.1080/02671520802524810 

Quintelier, E. & Blais, A. (2016). Intended and Reported Political Participation. International Journal of Public Opinion Research, 28(1), 117–128. doi: https://doi.org/10.1093/ijpor/edv017 

Quintelier, E. & Hooghe, M. (2013). The relationship between political participation intentions of adolescents and a participatory democratic climate at school in 35 countries. Oxford Review of Education, 39(5), 567–589. doi: https://doi.org/10.1080/03054985.2013.830097 

Resh, N. (2018). Sense of Justice in School and Social and Institutional Trust. Comparative Sociology, 14(3-4), 369–385. doi: https://doi.org/10.1163/15691330-12341465 

Resh, N. (2010). Sense of justice about grades in school: is it stratified like academic achievement? Social Psychology of Education, 13(3), 313–329. doi: https://doi.org/10.1007/s11218-010-9117-z 

Resh, N. & Dalbert, C. (2007). Gender Differences in Sense of Justice about Grades: A Comparative Study of High School Students in Israel and Germany. Teachers College Record, 109(2), 322–342. Recuperado de https://www.researchgate.net/profile/Nura_Resh/publication/286356463_Gender_differences_in_sense_of_justice_about_grades_A_comparative_study_of_high_school_students_in_Israel_and_Germany/links/5bad27e845851574f7ea9643/Gender-differences-in-sense-of-justice-about-grades-A-comparative-study-of-high-school-students-in-Israel-and-Germany.pdf 

Resh, N. & Sabbagh, C. (2017). Sense of justice in school and civic behavior. Social Psychology of Education, 20(2), 387–409. doi: https://doi.org/10.1007/s11218-017-9375-0 

Resh, N. & Sabbagh, C. (2016). Justice and Education. En C. Sabbagh & M. Schmitt (Eds.), Handbook of Social Justice Theory and Research (pp. 349–368). Springer US. doi: 10.1007/978-1-4939-3216-0 

Resh, N. & Sabbagh, C. (2014). Sense of justice in school and civic attitudes. Social Psychology of Education, 17 (1), 51–72. doi: https://doi.org/10.1007/s11218-013-9240-8

Resh, N. & Sabbagh, C. (2013). Justice, belonging and trust among Israeli middle school students. British Educational Research Journal, 40(6), 1036–1056. doi: https://doi.org/10.1002/berj.3129 

Resh, N. & Sabbagh, C. (2009). Justice in Teaching. En L. Saha & A. G. Dworkin (Eds.), International Handbook of Research on Teachers and Teaching (pp. 669–682). Springer US. doi: 10.1007/978-0-387-73317-3

Roberts, K. M. (2016). (Re)Politicizing Inequalities: Movements, Parties, and Social Citizenship in Chile. Journal of Politics in Latin America, 8(3), 125–154. doi: https://doi.org/10.1177/1866802X1600800305 

Rozas, J. & Somma, N. (2020). Determinantes de la protesta juvenil en Chile. Revista Mexicana de Sociología, 82(3), 673–703. doi: http://dx.doi.org/10.22201/iis.01882503p.2020.3.58506 

Ruiz, C. (2015). De nuevo la sociedad. Santiago de Chile: LOM Ediciones. 

Ruiz, C. & Boccardo, G. (2014). Los chilenos bajo el neoliberalismo. Clases y conflicto social. Santiago de Chile: Nodo XXI–Desconcierto.

Ruiz, C. & Caviedes, S. (2020a). Estructura y conflicto social en la crisis del neoliberalismo avanzado chileno. Espacio Abierto, 29(1), 86–101. Recuperado de http://repositorio.uchile.cl/handle/2250/175352 

Ruiz, C. & Caviedes, S. (2020b). La rebelión de los hijos de la modernización neoliberal. En R. Baño, H. Fazio, A. Mayol & C. Ruiz (2020), Análisis del año 2019 (pp. 27–47). Santiago de Chile: Departamento de Sociología Universidad de Chile. 

Sabbagh, C. & Resh, N. (2016). Unfolding Justice Research in the Realm of Education. Social Justice Research, 29(1), 1–13. doi: https://doi.org/10.1007/s11211-016-0262-1 

Sabbagh, C., Resh, N., Mor, M. & Vanhuysse, P. (2006). Spheres of Justice within Schools: Reflections and Evidence on the Distribution of Educational Goods. Social Psychology of Education, 9(2), 97–118. doi: https://doi.org/10.1007/s11218-005-3319-9 

Sampermans, D. & Claes, E. (2018). Teachers as role models in the political socialization process: How a good student–teacher relationship can compensate for gender differences in students’ gender equality attitudes. Citizenship Teaching and Learning, 13(1), 105–125. doi: https://doi.org/10.1386/ctl.13.1.105_1 

Sandoval, J. & Carvallo, V. (2019). Una generación «sin miedo»: análisis de discurso de jóvenes protagonistas del movimiento estudiantil chileno. Ultima década, 27(51), 225–257. doi: https://dx.doi.org/10.4067/S0718-22362019000100225 

Sandoval, J. & Carvallo, V. (2017). Discursos sobre política y democracia de estudiantes universitarios chilenos de distintas organizaciones juveniles. Revista Española de Ciencias Políticas, 43, 137–160. doi: https://doi.org/10.21308/recp.43.06 

Santos, H. & Elacqua, G. (2016). Segregación socioeconómica escolar en Chile: elección de la escuela por los padres y un análisis contrafactual teórico. Revista CEPAL, 119, 133–148. Recuperado de https://repositorio.cepal.org/handle/11362/40396 

Schlozman, K. L., Verba, S. & Brady, H. E. (2012). The Unheavenly Chorus: Unequal Political Voice and the Broken Promise of American Democracy. Princeton: Princeton University Press. doi: 10.2307/j.ctt7sn9z

Siavelis, P. M. (2016). Crisis of representation in Chile? Journal of Politics in Latin America, 8(3), 61–93. Recuperado de https://journals.sub.uni-hamburg.de/giga/jpla/article/view/1004/1011 

Somma, N. (2017). Protestas y conflictos en el Chile contemporáneo: Quince tesis para la discusión. En R. Araya & F. Ceballos (Eds.), Conflictos, controversias y disyuntivas (pp. 37–85). Santiago de Chile: TIRONI Asociados. Recuperado de http://sociologia.uc.cl/wp-content/uploads/2017/08/somma-2017-quince-tesis-conflicto-y-protesta.pdf 

Somma, N. & Bargsted, M. (2018). Political inequality in 38 countries: A distributional approach. Comparative Sociology, 17(5), 469–495. doi: https://doi.org/10.1163/15691330-12341475 

Somma, N. & Bargsted, M. (2015). La Autonomización de la Protesta en Chile. En C. Cox & J. C. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados (pp. 209–240). Santiago de Chile: Ediciones Universidad Católica de Chile. 

Somma, N. Bargsted, M., & Sánchez, F. (2020). Protest Issues and Political Inequality in Latin America. American Behavioral Scientist. doi: https://doi.org/10.1177/0002764220941233 

Somma, N. & Medel, R. (2017). Shifting Relationships Between Social Movements and Institutional Politics. En S. Donoso & M. von Bülow (Eds.), Social movements in Chile. Organization, trajectories & political consequences (pp. 29–61). New York: Palgrave Macmillan. 

Tarabini, A. (2015). La meritocracia en la mente del profesorado: un análisis de los discursos docentes en relación al éxito, fracaso y abandono escolar. Revista de la Asociación de Sociología de la Educación, 8(3), 349–360. Recuperado de https://ojs.uv.es/index.php/RASE/article/view/8389/7982 

Tateo, L. (2018). Ideology of Success and the Dilemma of Education Today. En A. Joerchel & G. Benetka (Eds.), Memories of Gustav Ichheiser. Theory and History in the Human and Social Sciences (pp. 157–164). Springer, Cham. doi: https://doi.org/10.1007/978-3-319-72508-6_9 

Toro, S. (2008). De lo épico a lo cotidiano: Jóvenes y generaciones políticas en Chile. Revista de ciencia política, 28(3), 143–160. doi: http://dx.doi.org/10.4067/S0718-090X2008000200006 

Toro, S. (2007). La inscripción electoral de los jóvenes en Chile. Factores de incidencia y aproximaciones al debate. En A. Fontaine, C. Larroulet, J. A. Viera-Gallo & I. Walker, Modernización del régimen electoral chileno (pp. 101–122). Santiago de Chile: Programa de las Naciones Unidas para el Desarrollo. Recuperado de https://www.cieplan.org/wp-content/uploads/2019/12/Modernizacion-del-regimen-electoral-chileno.pdf 

Treviño, E., Villalobos, C., Béjares, C. & Naranjo, E. (2019). Forms of Youth Political Participation and Educational System: The Role of the School for 8th Grade Students in Chile. YOUNG, 27(3), 279–303. doi: https://doi.org/10.1177/1103308818787691 

Valenzuela, J. P., Bellei, C. & de los Ríos, D. (2014). Socioeconomic school segregation in a market-oriented educational system. The case of Chile. Journal of Education Policy, 29(2), 217–241. doi: https://doi.org/10.1080/02680939.2013.806995

Van Deth, J. W. (2014). A conceptual map of political participation. Acta Polit 49(3), 349–367. doi: https://doi.org/10.1057/ap.2014.6 

Verba, S., Schlozman, K. L. & Brady, H. E. (1995). Voice and Equality. Civic Voluntarism in American Politics. Londres: Harvard University Press.

Walzer, M. (1983). Spheres of justice. New York: Basic Books.

Wanders, F. H. K., Dijkstra, A. B., Maslowski, R. & van der Veen, I. (2020). The effect of teacher-student and student-student relationships on the societal involvement of students. Research Papers in Education, 35(2), 1–21. doi: https://doi.org/10.1080/02671522.2019.1568529  

Wanders, F. H. K., van der Veen, I., Dijkstra, A. B. & Maslowski, R. (2020). The influence of teacher-student and student-student relationships on societal involvement in Dutch primary and secondary schools. Theory & Research in Social Education, 48(1), 101–119. doi: https://doi.org/10.1080/00933104.2019.1651682 

Youniss, J. & Levine, P. (2009). Engaging young people in civic life. Nashville: Vanderbilt University Press.

Zarzuri, R. (2016). Las transformaciones en la participación política de los jóvenes en el Chile actual. En M. A. Garretón (Ed.), La gran ruptura. Institucionalidad política y actores sociales en el Chile del siglo XXI (pp. 133–160). Santiago de Chile: LOM Ediciones.
